//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyMaintenances.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public string Asset_SN { get; set; }
        public string Detail_name { get; set; }
        public string Department { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Description { get; set; }
        public string Considerations { get; set; }
        public string Technician_Note { get; set; }
        public Nullable<System.DateTime> Completed_on { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Detail Detail { get; set; }
    }
}
